### PR TITLE
Remove Tasks that are for EOL PE (SUP-2431)

### PR DESCRIPTION
**Pull request by MartyEwings**
Prior to this commit there where tasks in the bundle for EOL versions. These have been removed

delete mode 100644 tasks/st0244_disable_mco_logrotate.json
 delete mode 100644 tasks/st0244_disable_mco_logrotate.sh
 delete mode 100644 tasks/st0299_regen_master_cert.json
 delete mode 100644 tasks/st0299_regen_master_cert.sh

This commit also has some house keeping on the readme, moving the task descriptions to REFERENCE.MD for puppet-strings compatibility

### CODE REVIEW

**Review by gavindidrichsen — CHANGES_REQUESTED** [review]
Could you possibly add a tag just prior to the delete of these tasks and then also some sort of FYI reference in the README to allow users to easily look back at the old tasks if needed.

**Comment by MartyEwings** [comment]
@gavindidrichsen good call, but hte label thats been applied "backwards-incompatible" will generate a release log and a major version indicating backwards incompatibility the next time we run the release automation, so we don't need to manually do things like that anymore

**Comment by gavindidrichsen** [comment]
> ...so we don't need to manually do things like that anymore

Nice!

**Review by gavindidrichsen — APPROVED** [review]

**Comment by MartyEwings** [comment]
waiting on corresponding article removal

**Pull request merged**
