### PR TITLE
Remove ca_extend plans and tasks from this module.

### PR DESCRIPTION
**Pull request by m0dular**
They now live in puppetlabs-ca_extend on the Forge.

This reverts commit 3d7904f780cc657851cb50173833869a0cd68072, reversing
changes made to 9eaa0f955664c0ea65209f4f24c0dfbb440e13fb.

### CODE REVIEW

**Comment by jarretlavallee** [comment]
Looks good, pending CI. There is still a reference to the KB in the readme that needs to be removed.

**Comment by m0dular** [comment]
@jarretlavallee Bah, good catch.  The KB actually still lives and just got updated, so how should we handle that?  The `README` still links to the correct article

**Comment by jarretlavallee** [comment]
I would say to remove it since it is no longer implemented here and the KB will be updated to point to the module.

The failure in CI looks to be a resource issue. I am restarting it.

**Comment by jarretlavallee** [comment]
We should also consider the semver for the version. Might be able to sneak it into a minor release.

**Comment by MartyEwings** [comment]
@m0dular it looks like we have this version released already in the forge, but we need the change log  updated to match the changes, and the other new tasks since the previous releases. can you do this in this PR? if not ill merge this in a update separately

**Pull request merged**
