### PR TITLE
(SUP-2539) Update terminology and refactor

### PR DESCRIPTION
**Pull request by m0dular**
This commit replaces references to "master" with "primary" and refactors
the script to regenerate the primary cert.

### CODE REVIEW

**Review by MartyEwings — APPROVED** [review]
looks good to me so long as its tested

**Comment by MartyEwings** [comment]
@m0dular looks like as have a failing shell check,

**Comment by m0dular** [comment]
Ah that's from st1096, but I can fix it in this PR :+1:

**Comment by m0dular** [comment]
Gave it a quick test on 2021 and 2019 :+1:

**Pull request merged**
