### PR TITLE
Add windows find disabled agents ps1

### PR DESCRIPTION
**Pull request by cwebster61083**

### CODE REVIEW

**Comment by cwebster61083** [comment]
Marty, 

Very good point. I will get a metadata file added for Powershell tomorrow most likely and update the PR.

**Comment by cwebster61083** [comment]
@MartyEwings would you recommend that I follow the bellow pattern.
kb0285_find_disabled_agents.json
kb0285a_bash_find_disabled_agents.json 
kb0285b_powershell_find_disabled_agents.json

**Comment by MartyEwings** [comment]
Dealer's choice, works for me!

**Comment by cwebster61083** [comment]
@MartyEwings I have pushed the changes you requested. Let me know if it needs any additional changes.

**Pull request merged**
