### PR TITLE
(maint) Prepare for travis to deploy the module to the forge

### PR DESCRIPTION
**Pull request by jarretlavallee**
This PR is aimed at configuring travis to be able to deploy this module to the forge when a new `/^v\d`/` tag has been added.

### CODE REVIEW

**Comment by jarretlavallee** [comment]
@MartyEwings I moved the litmus config into the `.sync.yml` to add some capabilities around the deploy feature from travis. We should be able to use travis to deploy the module to the forge. The next steps are:

1. Add the deploy password to travis: https://github.com/puppetlabs/pdk-templates#travisyml
2. Add that encrypted string to the `.sync.yml` in the `.travis.yml => secure` value.
3. Deploy a new version of the module by adding a `v##` tag to the master branch.

What do you think about this approach?

**Comment by MartyEwings** [comment]
@jarretlavallee great! Between this and the testing we cut a bunch of manual intervention from the process, the easier to deploy, the more chance we will contribute.

One thing I noticed was since I added the complex containers with systemd enabled, travis takes loads of time to complete checks, what are your thoughts on that?  I don't think it'll go up more with more tests, seems to be the container provisioning taking the time

**Comment by MartyEwings** [comment]
@jarretlavallee Also the repo is public now, is that an issue for the secrets? Or are they obfuscated in someways

**Comment by jarretlavallee** [comment]
It looks like only the EL images are taking longer. We are seeing those two jobs take 20+ minutes. It is hanging on booting those containers for about 7.5 minutes (about 2 minutes per container). We then hit the same 8ish minutes for the acceptance testing of these containers. It does not happen with the debian containers with systemd. 

I don't think it will go up further, but maybe we should scale back what we test on for the EL systems. Perhaps getting rid of oracle and scientific? That would reduce it a good amount.

**Comment by jarretlavallee** [comment]
Removing ScientificLinux cut it down from 20 minutes to 15 minutes. In theory, removing Oracle will bring it down to 10 minutes, but we should probably fix the docker images to increase the speed and leave those OS in the testing.

The dockerfiles are in <https://github.com/puppetlabs/litmus_image> so I will take a look.

**Pull request merged**
